// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_chat from "./routes/api/chat.ts";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_logout from "./routes/auth/logout.ts";
import * as $chat_id_ from "./routes/chat/[id].tsx";
import * as $chat_new from "./routes/chat/new.tsx";
import * as $index from "./routes/index.tsx";
import * as $ChatArea from "./islands/ChatArea.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/chat.ts": $api_chat,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/logout.ts": $auth_logout,
    "./routes/chat/[id].tsx": $chat_id_,
    "./routes/chat/new.tsx": $chat_new,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ChatArea.tsx": $ChatArea,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
